var GAME_LEVELS = [
["                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"    @                                                 ",
"                                                      ",],//Welcome screen
["          !                     x          x          x          x",
"          !                     x          x    o     x          x",
"          x               !                x          x          x",
"          x     o                    b     x     h    x          x",
"          !          x                                x          x",
"          x                   x            x          x          x",
"                     x                                x          x",
"      o                      H  x                     x     o    x",
"          x          x          x                     x          x",
"          x     h    x          x     o    x          x          x",
"   b      x          !          x    !     x          x          x",
"          !          x          x          x          x          x",
"          x          x       o  x      H   x                     x",
"  @                             !          x                     x",
"                         !      !          x          x          x",
"     !                         x             !       !          x",
"              !                !          x          x          x",
"                         !           x          !    x          x",
"                 x              !          x          x          x",],

 [ "         oooooooooooooooooooooooooooooo                               ",
   "         oooooooooooooooooooooooooooooo                               ",
   "         oooooooooooooooooooooooooooooo                               ",
   "         oooooooooooooooooooooooooooooo                               ",
   "         oooooooooooooooooooooooooooooo                               ",
   "     ooooooooooooooooooooooooo                                              ",
   "   oooooooooooooooooooo           xxx           ",
   "    oooooooooooooooooooo                                               xx      xx    xx!xx          ",
   "      oooooooooooooooooooooooo    o o      xx                  x!!!x          ",
   "      oooooooohooooooooooooooooooooooo                    xx!xx          ",
   "   ooooooooooooooooooooooooxxxxx                          xvx           ",
   "      oooooooooooooooooooooooooooo                                     xx  ",
   "oooooooooooooooooooooooooooo            o o                                x  ",
   " oooooooooooooooooooooooo                                                    x  ",
   "      oooooooo      oooo                                                    x  ",
   "   oooooooooooooooo                   xxxxx                             o x  ",
   "  h            bbbb x   o                                                    x  ",
   "    @    bbbb x   p                                            xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                 oooooooo                      x     x            xxxxxxx        xxx         xxx                  ",
   "           oooooooo                            x     x                           x x         x x                  ",
   "               oooooooo                       x     x                             x         x                    ",
   "          oooooooo                            x     x                             xx        x                    ",
   "             oooooooo                          xx    x                             x         x                    ",
   "      oooo oooo                                x     x      o  o     x   x         x         x                    ",
   "       ooooooooxxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "      ooooooooxx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "   oooooooo  xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "          o                                                   xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x  o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                                     x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x                                     x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
   ["                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"    @                                                 ",
	"                                                      ",],
	["                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"    @                                                 ",
	"                                                      ",]
   
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
